AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 basic skeleton cu TODO-uri pt. invatare"

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC-ul in care lansezi instanta"
    Default: vpc-00d25ec03889f4783   # <-- optional, pune-l pe al tau sau sterge linia
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: "Subnet public (auto-assign public IP ON)"
    Default: subnet-0ff6bdc78ca5704b3
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t2.micro
      - t3.micro
    Description: "Alege un tip Free Tier, ex: t3.micro"
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
    Description: "Amazon Linux 2023 (x86_64) AMI dinamic via SSM"

Resources:
  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "SG pt. instanta demo permite SSH"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0     # pentru test. Ideal: inlocuieste cu IP-ul tau /32

  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref InstanceSG
      Tags:
        - Key: Name
          Value: cfn-ec2-demo

Outputs:
  InstanceId:
    Value: !Ref Ec2Instance
    Description: "ID-ul instanței"
  PublicIP:
    Value: !GetAtt Ec2Instance.PublicIp
    Description: "IP public (daca subnetul aloca IP public)"